### ISSUE TITLE
EOFError: end of file reached

### ISSUE THREAD

**Issue by pdrowr** [SliceDevelopers/keppler_admin#11]
Error al intentar enviar un mail usando la gema ContactUs:

![eof](https://user-images.githubusercontent.com/28924639/29130567-447c1ea4-7cf8-11e7-82d5-2af59d90ceab.png)

Solución:
Configurar El Simple Mail Transfer Protocol (Configuración > Configuración de Email (SMTP)) desde el Admin de Keppler.

**Comment by gbrlmrllo** [comment]
Estos errores los estan arreglando directamente desde master?
