### ISSUE TITLE
Reactivar y estilizar notificaciones - Noty

### ISSUE THREAD

**Issue by enmachs** [SliceDevelopers/keppler_admin#123]
## Historia de usuario
**Como** admin.
**Quiero** recibir pequeñas notificaciones al realizar alguna acción dentro del keppler.
**Para** saber y estar al tanto si el proceso fue realizado o no.

## Objetivos
- Hacer funcionar las notificaciones nuevamente.
- Darles un nuevo estilo acorde a su entorno. 
- Mejorar ux.

## Condiciones
- Utilizar alguna librería externa para unas mejores animaciones.

**Comment by anyelopetit** [comment]
Ya hice merge con el PR de este issue, pero ¿podrías colocar los notys en el medio? @enmachs a la izquierda tapan el logo y a la derecha podrían obstaculizar el botón de nuevos registros.
