### ISSUE TITLE
Al borrar un usuario, todos los registros que le pertenezcan deben pasarse al admin.

### ISSUE THREAD

**Issue by anyelopetit** [SliceDevelopers/keppler_admin#18]
"Al borrar un usuario el blog explota, porque no encuentra el usuario que creó el post, en ese caso, al borrar un usuario, se debe buscar todo lo que tiene ese usuario y asignarselo al id 1 que es el admin."
- Eduardo Meléndez

**Comment by gbrlmrllo** [comment]
Este issue creo que deberia estar escrito en el repositorio del blog engine.

**Comment by anyelopetit** [comment]
En la gema del keppler_blog?

2017-09-13 14:41 GMT-04:00 Gabriel Morillo <notifications@github.com>:

**Comment by gbrlmrllo** [comment]
Si.
