### ISSUE TITLE
[Error] De autorización del dashboard (google analytics)

### ISSUE THREAD

**Issue by anyelopetit** [SliceDevelopers/keppler_admin#5]
![pasted image at 2017_06_24 06_10 pm](https://user-images.githubusercontent.com/19691938/27931621-cf49db8e-6268-11e7-9f02-a84f4d8e7287.png)

**Comment by luprz** [comment]
Esto es un fallo en la autentificacion de google analytic en el dashboard.. Esto puede ser generado por un error en el archivo .p12 o por un error service_account_email_address en el archivo "secrets.yml"..

Solucion:

Revisar si esta bien escrito el service_account_email_address
Verificar que el archivo p12 pertenezca a ese service_account_email_address
