### ISSUE TITLE
Cambio de posición de registros con 'drag and drop'

### ISSUE THREAD

**Issue by luprz** [SliceDevelopers/keppler_admin#85]
# User Story

**Como** Admin
**Quiero** poder cambiar la posición de la lista de un registro
**Para** ordenarlos como me sean útiles

# Objetivos

* Permitir que el usuario pueda cambiar de posición un registro
* Hacer cómodo al usuario el cambio de posición de un registro

# Condiciones

* Esta función solo lo pueden tener los módulos generados por scaffolds
* Un registro no puede tener mas de una posición
* Dos o mas registros no pueden tener una misma posición

# Flujo

1) Hacer clic al icono de mover en el registro
2) Arrastrar el registro hacia arriba o hacia abajo y situarlo en la posición que desea
3) Soltar

# Recomendaciones

* Reutilizar el código desarrollado @EnmChs 
* Utilizar el metodo 'drag and drop'

# Dificultad

* Pasar un registro de una pagina a otra usando 'drag and drop'

**Comment by anyelopetit** [comment]
@enmchs ¿puedes hacer esta función para los demás módulos?

**Comment by luprz** [comment]
@anyelopetit donde esta el PR de esto?
