### ISSUE TITLE
Error en la vista de meta tags

### ISSUE THREAD

**Issue by EnmChs** [SliceDevelopers/keppler_admin#9]
Al tener un meta tag registrado y querer ingresar a la vista index de los mismos, arroja error de una ruta no definida.
![captura de pantalla de 2017-08-09 00-39-23](https://user-images.githubusercontent.com/25708238/29105611-0199d5a0-7c9d-11e7-8768-36272f2d8533.png)

**Comment by gbrlmrllo** [comment]
Porbablemente sea un problema con la version.
