### ISSUE TITLE
Agregar funcionalidad borrado múltiple en módulos restantes

### ISSUE THREAD

**Issue by EnmChs** [SliceDevelopers/keppler_admin#91]
## Historia de usuario
**Como** admin
**Quiero** poder eliminar mutiples item al mismo momento en cualquier módulo de keppler_admin
**Para** tener el feature habilitada en cada uno de éstos. 

## Objetivos
- Hacer más rápido el flujo dentro de la aplicación

## Flujo
- Seleccionar múltiples items en cualquier módulo
- Presionar botón eliminar y borrar todos los items previamente seleccionados

**Comment by luprz** [comment]
Esto le falta descripcion.. desarrolla mas este requerimiento @EnmChs.. usa el formato
